2023-01-25 13:15:26,114 Downloading artifact
Traceback (most recent call last):
  File "pyarrow/pandas-shim.pxi", line 109, in pyarrow.lib._PandasAPIShim._check_import
  File "pyarrow/pandas-shim.pxi", line 48, in pyarrow.lib._PandasAPIShim._import_pandas
  File "/home/bialekm/miniconda3/envs/mlflow-7b091c2446f7e0c648cdd69efeccc7514521724f/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 1027, in <module>
    'floating': np.float,
  File "/home/bialekm/miniconda3/envs/mlflow-7b091c2446f7e0c648cdd69efeccc7514521724f/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'
Exception ignored in: 'pyarrow.lib._PandasAPIShim._have_pandas_internal'
Traceback (most recent call last):
  File "pyarrow/pandas-shim.pxi", line 109, in pyarrow.lib._PandasAPIShim._check_import
  File "pyarrow/pandas-shim.pxi", line 48, in pyarrow.lib._PandasAPIShim._import_pandas
  File "/home/bialekm/miniconda3/envs/mlflow-7b091c2446f7e0c648cdd69efeccc7514521724f/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 1027, in <module>
    'floating': np.float,
  File "/home/bialekm/miniconda3/envs/mlflow-7b091c2446f7e0c648cdd69efeccc7514521724f/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__